#! /bin/bash

copy_dir()
{	
	#in parameters
	file=$1
	tar_file=$2
	dry_run=$3

	#if directory to copy is a file
	if [ -f "$file" ]
	then
		found=0
		#search if the file is in the directory 
		for j in $files_inside
		do
			if [ "$j" == "$file" ]
			then
				found=1
			fi
		done

		#if find add the date to the end of the name
		if [ $found -eq 1 ]
		then
			date_name=$(date +"%y%m%d")
			if [ $dry_run -eq 1 ]
			then
				echo "->File '${file}' already exists inside '${tar_file}'. Adding it as '${file}.${date_name}'."
			else
				name="$file"."$date_name"
				mv "$file" "$name"
				tar -upf $tar_file $name &> /dev/null
				mv "$name" "$file"
			fi
		
		#if dry run just print message
		else
			if [ $dry_run -eq 1 ]
			then
				echo "->File '${file}' does not exist inside '${tar_file}'. Adding it."
			else
				tar -upf $tar_file $file &> /dev/null
			fi
		fi

	#if directory to copy is a folder begin copy_dir again
	elif [ -d "$file" ]
	then
		for entry in "${file}"/*
		do
			copy_dir $entry $tar_file $dry_run  
		done
	fi
}

#Copia [-K] [-D] fitxer1 fitxer2 ... fitxer_tgz

#Limit cases:
#1: -D and -K are valid names but cannot be the first ones,
# as they will get interpreted as flags.
#2: last file should always be *.tgz or *.tar.gz

# Error when no arguments
if [ $# -eq 0 ]
then
	echo "Error: Enter arguments."
	exit 1
fi

# Error when "./Copia -K" or when "./Copia -K -D"
date=0
dry_run=0
n=0
if [ $1 = "-K" ]
then
	#if only parameter is -K print error
	if [ $# -eq 1 ]
	then
		echo "Error: Flag without files."
		exit 1
	else
		#if there's the -D too
		if [ $2 = "-D" ]
		then
			#if there is only the -K and -D print error
			if [ $# -eq 2 ] 
			then
				echo "Error: Flags without files."
				exit 1
			fi
			let "n++"
			dry_run=1 #set flag dry_dry to true
		fi
	fi
	let "n++"
	date=1 #set flag date to true
fi

# Error when "./Copia -D" or when "./Copia -D -K"
if [ $1 = "-D" ]
then
	#if there is only the -K and -D print error
	if [ $# -eq 1 ]  
	then
		echo "Error: Flag without files."
		exit 1
	else
		#if there's the -D too
		if [ $2 = "-K" ]
		then
			#if there is only the -D and -K print error
			if [ $# -eq 2 ]
			then
				echo "Error: Flags without files."
				exit 1
			fi
			let "n++"
			date=1 #set glag date to true
		fi
	fi
	let "n++"
	dry_run=1 #set flag dry_run to true
fi

# Error if last argument does not end with *.tgz or *.tar.gz
for i in "$@"; do :; done

if [[ "$i" != *.tgz ]]
then
	if [[ "$i" != *tar.gz ]]
	then
		echo "Error: Last file should have the extension .tgz or .tar.gz"
		exit 1
	fi
fi

# We set the last argument to tar_file
tar_file=$i

# Here check if there are files to make a copy
let n_files=$#-$n
if [ $n_files -eq 1 ]
then
	echo "Error: No files to make a copy."
	exit 1
fi

# We shift left n arguments (remove the flags we had).
shift $n

# Get all the arguments except the last one.
files_to_store=${@:1:$((${#}-1))}

# If the .tgz or .tar.gz already exists and we need to add files to it,
# or if we will create a new .tgz or .tar.gz
create_tar=0
files_inside=
if [ ! -f $tar_file ]
then
	create_tar=1
else
	# Is the tar_file really valid?
	tar -tf "$tar_file" &> /dev/null
	if [ $? -eq 0 ]
	then
		files_inside=$(tar -tf $tar_file) #safe the files in files_inside
	else
		echo "Error: The existing tar file is not valid! Stopping the process to prevent potential data lose."
		exit 2
	fi
fi

#grab que path of the current diroectory
abs_path=$(pwd)
#if de tar dont exist
if [ $create_tar -eq 1 ]
then
	#if dry_run is true print message
	if [ $dry_run -eq 1 ]
	then
		echo "->Creating ${tar_file}."
	#if not create tar_file
	else
		touch $tar_file 
	fi
	#loop throw the files in files_to_store
	for i in $files_to_store
	do
		# if exists
		if [ -e "$i" ]
		then
			file=$i
			#check if the path begins like it should
			if [[ "$i" == $abs_path* ]]
			then
				file=${i#"${abs_path}/"}
				#if dry_run is true show message
				if [ $dry_run -eq 1 ]
				then
					echo "->Absolute path detected. Compressed from '${i}' to '${file}'."
				fi
			fi
			#if is a file
			if [ -f "$file" ]
			then
				# if dry_run is true show message
				if [ $dry_run -eq 1 ]
				then
					echo "->File '${file}' exists. Adding it to '${tar_file}'."
				# if not 
				else
					tar -upf $tar_file $file &> /dev/null
				fi
			#if is a directory
			elif [ -d "$file" ]
			then
				# if dry_run is true whoe message
				if [ $dry_run -eq 1 ]
				then
					echo "->Directory '${file}' exists. Adding it to '${tar_file}'."
				else #if not 
					tar -upf $tar_file $file &> /dev/null #update if the last modifyed date is more current than the existing file
				fi
			else
				#if dry_run show message
				if [ $dry_run -eq 1 ]
				then
					echo "->Error, '${file}' is neither file nor directory."
				fi
			fi
		else
			#if dry_run show message
			if [ $dry_run -eq 1 ]
			then
				echo "->Error, '${i}' does not exist."
			fi
		fi
	done
#if tar_file alredy exists
else
	#if dry_run show message
	if [ $dry_run -eq 1 ]
	then
		echo "->${tar_file} already exists."
	fi
	#loop through all the files in files_to_store
	for i in $files_to_store
	do
		#if i exists compress it
		if [ -e "$i" ]
		then
			file=$i
			if [[ "$i" == $abs_path* ]]
			then
				file=${i#"${abs_path}/"}
				if [ $dry_run -eq 1 ]
				then
					echo "Absolute path detected. Compressed from '${i}' to '${file}'."
				fi
			fi
			#if date flag is true
			if [ $date -eq 1 ]
			then
				#if is a folder grab the files and go cpoy_dir
				if [ -d "$file" ]
				then
					last_char="${file: -1}"
					if [ "$last_char" == "/" ]
					then	
						dir=${file::-1}
					else
						dir=$file
					fi
					copy_dir $dir $tar_file $dry_run
				#if is a file just copy_dir
				else
					copy_dir $file $tar_file $dry_run
				fi
			#if date flag is false and the directory exists
			else
				if [ -f "$file" ] #if is a file update it
				then
					if [ $dry_run -eq 1 ]
					then
						echo "->File '${file}' exists. Updating it inside '${tar_file}'."
					else
						tar -upf $tar_file $file &> /dev/null #update if the last modifyed date is more current than the existing file
					fi
				elif [ -d "$file" ] #if is a folder update it
				then
					if [ $dry_run -eq 1 ]
					then
						echo "->Directory '${file}' exists. Updating it inside '${tar_file}'."
					else
						tar -upf $tar_file $file &> /dev/null #update if the last modifyed date is more current than the existing file
					fi
				else #if it is not a folder or a file print error
					echo "->Error, '${file}' is neither file nor directory."
				fi
			fi
		else #if it does not exist and dry_run, print message
			if [ $dry_run -eq 1 ]
			then
				echo "->Error, '${i}' does not exist."
			fi
		fi
	done
fi

# Check if the tar created is empty. If it is, delete it
if [ $dry_run -eq 0 ]
then
	tar -tf $tar_file &> /dev/null
	if [ ! $? -eq 0 ]
	then
		rm -rf $tar_file
	fi
fi

